<a href="https://colab.research.google.com/github/bugatha1/Tensorflow/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow

It is end-to-end open source platform for machine learning.<br>
Able to access many prebuild/pretrained deep learing models<br>
Designed by Google

# Tensor
A Tensor is a way to represents some sort of data into numerical form.

In [1]:
import tensorflow as tf
tf.__version__

'2.8.0'

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix (more than one dimension)
matrix = tf.constant([[10, 10], 
                      [20, 20]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 20]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10, 10],
                             [20, 20],
                             [10, 20]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 10.],
       [20., 20.],
       [10., 20.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
another_tensor = tf.constant([[[10, 10], [12, 12]],
                             [[20, 20], [12, 23]],
                             [[10, 20], [2, 3]]])
another_tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10, 10],
        [12, 12]],

       [[20, 20],
        [12, 23]],

       [[10, 20],
        [ 2,  3]]], dtype=int32)>

In [11]:
another_tensor.ndim

3

Scalar : a single number <br>
Vector : a number with direction<br>
Matrix : a 2-dimensional array of numbers<br>
Tensor : n-dimensional (0 dimensional tensor is scalar, 1 dimensional tensor is vecors..so on..)<br>
 

# Create tensors with tf.variable

In [12]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeable_tensor[0].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7], dtype=int32)>

# Turn Numpy arrays to tensors
The main difference between NumPy arrays and TensorFlow is tensor can run on GPU (much faster for numerical computing)

In [14]:
# Create numpy array between 1 to 25

import numpy as np

numpy_arr = np.arange(1, 25, dtype=np.int32)
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [15]:
A = tf.constant(numpy_arr)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [16]:
B = tf.constant(numpy_arr, shape=(2, 3, 4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [17]:
B.ndim

3

In [18]:
A.ndim

1

In [19]:
numpy_zero4 = np.zeros(shape=[2, 3, 4])
numpy_zero4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
numpy_zero3 = np.ones(shape=[2, 3, 4])
numpy_zero3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
tensor_zero4 = tf.zeros(shape=[2, 3, 4])
tensor_zero4

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [22]:
tensor_zero3 = tf.ones(shape=[2, 3, 4])
tensor_zero3

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [23]:
numpy_zero3.shape, numpy_zero3.ndim

((2, 3, 4), 3)

In [24]:
tensor_zero3.shape, tensor_zero3.ndim

(TensorShape([2, 3, 4]), 3)